apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/codefresh/cap-app-proxy
  newName: <private_registry>/cap-app-proxy
- name: alpine
  newName: <private_registry>/alpine

resources:
- https://github.com/codefresh-io/csdp-official.git/csdp/hybrid/basic/apps/app-proxy?ref=0.1.20
