apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/codefresh/cap-app-proxy
  newName: <private_registry>/cap-app-proxy
  newTag: 1.2056.0
- name: alpine
  newName: <private_registry>/alpine
  newTag: '3.16'
- name: quay.io/codefresh/applicationset
  newName: <private_registry>/applicationset
  newTag: v0.4.2-CR-13254-remove-private-logs

resources:
- github.com/codefresh-io/csdp-official.git/csdp/hybrid/basic/apps/app-proxy?ref=0.1.20
