apiVersion: codefresh.io/v1alpha1
kind: Runtime
metadata:
  name: "{{ name }}"
  namespace: "{{ namespace }}"
spec:
  requiredCLIVersion: ^0.1.0
  version: 0.1.20
  bootstrapSpecifier: github.com/odefresh-contrib/internal-runtime-def-example/manifests/argo-cd?ref=CR-14461-use-token
  components:
  - name: events
    type: kustomize
    url: github.com/odefresh-contrib/internal-runtime-def-example/manifests/argo-events?ref=CR-14461-use-token
    wait: true
  - name: rollouts
    type: kustomize
    url: github.com/odefresh-contrib/internal-runtime-def-example/manifests/argo-rollouts?ref=CR-14461-use-token
  - name: workflows
    type: kustomize
    url: github.com/odefresh-contrib/internal-runtime-def-example/manifests/argo-workflows?ref=CR-14461-use-token
  - name: app-proxy
    type: kustomize
    url: github.com/odefresh-contrib/internal-runtime-def-example/manifests/app-proxy?ref=CR-14461-use-token
    syncWave: 9
  - name: internal-router
    type: kustomize
    url: github.com/odefresh-contrib/internal-runtime-def-example/manifests/internal-router?ref=CR-14461-use-token
    syncWave: 10
  - name: sealed-secrets
    type: kustomize
    url: github.com/odefresh-contrib/internal-runtime-def-example/manifests/sealed-secrets?ref=CR-14461-use-token
  - name: codefresh-tunnel-client
    type: helm
    url: github.com/odefresh-contrib/internal-runtime-def-example/manifests/codefresh-tunnel-client
    feature: ingressless
