apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/codefresh/argocli
  newName: <private_registry>/codefresh/argocli
- name: quay.io/codefresh/argoexec
  newName: <private_registry>/codefresh/argoexec
- name: quay.io/codefresh/workflow-controller
  newName: <private_registry>/codefresh/workflow-controller

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: workflow-controller
  patch: |
    - op: replace
      path: /spec/template/spec/containers/0/args/3
      value: <private_registry>/codefresh/argoexec:v3.4-cap-CR-15902

resources:
- https://github.com/codefresh-io/csdp-official.git/csdp/hybrid/basic/apps/argo-workflows?ref=0.1.24
