apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/codefresh/argocd
  newName: <private_registry>/argocd
- name: ghcr.io/dexidp/dex
  newName: <private_registry>/dex
- name: quay.io/codefresh/redis
  newName: <private_registry>/redis
- name: quay.io/codefresh/applicationset
  newName: <private_registry>/applicationset

patches:
# Istio protocol selection: https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/
# Ovveride the default protocol selection which is done by the port name (http), since this port is being used for both http and grpc.
- target:
    version: v1
    kind: Service
    name: argocd-server
  patch: |
    - op: add
      path: /spec/ports/0/appProtocol
      value: tcp

namespace: default
resources:
- https://github.com/codefresh-io/csdp-official.git/csdp/hybrid/basic/apps/argo-cd?ref=0.1.24
